
services:
  backend:
    restart: always
    user: root
    env_file: .env
  
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPORT=${DBPORT}
      - DBHOST=${DBHOST}
      - DBPASSWORD=${DBPASSWORD}
      - EMAIL_USER=${EMAIL_USER}       
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: daphne -v 0 -b 0.0.0.0 -p 8000 kykam_agencies.asgi:application
    volumes:
      - ./backend:/app
      - ./media:/app/media
      - static_volume:/app/staticfiles/
    working_dir: /app
    container_name: backend
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - kykam_network

  db:
    image: postgres:15-alpine  # Use a standard image instead of 'build'
    container_name: db
    restart: always
    ports:
      - '5434:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DBNAME}
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASSWORD}
    networks:
      - kykam_network

  redis:
    image: redis:alpine
    restart: always
    expose:
      - 6379
    networks:
      - kykam_network  # Changed from mynetwork

networks:
  kykam_network:
    driver: bridge

volumes:
  pgdata: {}
  static_volume: {}
  media_volume: {}