version: "3.9"

services:
  # --- DATABASE ---
  db:
    image: postgres:15-alpine
    container_name: kykam_db
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DBNAME}
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASSWORD}
    networks:
      - kykam_network

  # --- CACHE ---
  redis:
    image: redis:alpine
    container_name: kykam_redis
    restart: always
    networks:
      - kykam_network

  # --- DJANGO BACKEND ---
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: kykam_backend
    restart: always
    env_file: .env
    # Daphne handles ASGI for real-time features
    command: daphne -b 0.0.0.0 -p 8000 kykam_agencies.asgi:application
    volumes:
      - static_volume:/app/staticfiles
      - ./media:/app/media
    # expose:
    #   - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - kykam_network

  # --- NGINX (GATEKEEPER) ---
  nginx:
    image: nginx:alpine
    container_name: kykam_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - static_volume:/app/staticfiles:ro
      - ./media:/app/media:ro
      - ./frontend/kykam_frontend/dist:/usr/share/nginx/html:ro
      # Fix: Only use the relative path for portability
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    depends_on:
      - backend
    networks:
      - kykam_network
networks:
  kykam_network:
    driver: bridge

volumes:
  pgdata:
  static_volume: